language: node_js
node_js:
- lts/*
os:
- linux
dist: focal
branches:
  only:
  - master
  - /v\d+\.\d+[a-z]/
cache: yarn
before_install:
  - npm install --g npm
script:
  - yarn lint --fix
  - npm install
  - npm run pretest
deploy:
  provider: heroku
  api_key: $HEROKU_AUTH_TOKEN
  app: $APP
  on:
    repo: $REPOSITORY
    all_branches: true
