language: node_js
node_js:
- lts/*
os:
- linux
dist: focal
branches:
  only:
  - master
  - /v\d+\.\d+[a-z]/
cache: yarn
script:
  - yarn lint --fix
  - $API
deploy:
  provider: heroku
  api_key: $HEROKU_AUTH_TOKEN
  app: $APP
  on:
    repo: $REPOSITORY
