language: node_js
node_js:
  - lts/*

os:
  - linux
dist: focal

branches:
  only:
    - main
    - master

cache: yarn

script:
  - yarn lint --fix
  # - yarn wdio

deploy:
    provider: heroku
    api_key:
    app: projectdesenv
    on:
      repo: CallyCa/PrototypeNuxt
