language: node_js
node_js:
- lts/*
os:
- linux
dist: focal
branches:
  only:
  - main
  - master
cache: yarn
script:
- yarn lint --fix
deploy:
  provider: heroku
  api_key:
    secure: kmTQdqhEnDa4ZQrfZZwAeQRrk3YnM5IA+iYjBPA3GFHaNOjtHIb14X4CkAvjfjDZR2IrQz90P/tNyXlrSGMHPqjeeIK0RUY0aLkrWOevl3Yd/+UqvRr1RAji1vtjnMicZ912My+BAoHbf/wFhOBoug/vUrA7KzBU3xGPZwDjTw9Q8BCrQbK0PdiwLO88YUvMZimri6XzVtouCl/09K9PdAtxa3qLwYA7H/says2TRYTXnQfV6KouBIoPjQPvdTRXBn1zaGLlQPvjU/0R6KQQGPPfBJNmjxDZNUJq7r+L0e3wzL8ypFVh4lJuV3Oxf2ENA5lYnJf6SVcbjezYDSEmbURnd2Qk1u2X37UKQhvwv+8RhNRC9Ro3sOi+Gpj/vz9CX8OF3S7O85bX8+WPy5OjXGdMNG2kmxTyKHElIEc0wS82jAobd0l5c3fXQ2toWEBERzXe+5mkn2Jreid1mdyG+tML11pN6GsbZfdk8VDttVXLf4q7WN130Nec4o62OXAFKHWtGm96i73GTqrnmibl/sBjxz23T/3eNkaarO0SQON2F+VCrlzIGvefwc+qvYaMClZV2m46E0n0X5eIdZngamT9l9WZcwWcXyfiuTbw/QD5duDdXx7L3amN5lRBY5/wybHA0EXO+0D9tC4Xyy84qAxAgu7eFymSUzDmwnJ/Ig8=
  on:
    repo: CallyCa/PrototypeNuxt
